name: Build LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Rename PDF with timestamp
        run: mv main.pdf document_${TIMESTAMP}.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdf-${{ env.TIMESTAMP }}
          path: document_${{ env.TIMESTAMP }}.pdf
